version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: "javascript"
      directory: "/examples/basic"
      update_schedule: "daily"
      commit_message:
        prefix: "chore"
        include_scope: true
  - package_manager: "javascript"
        directory: "/examples/typescript"
        update_schedule: "daily"
        commit_message:
          prefix: "chore"
          include_scope: true
