name: Merge Dependabot PRs
on: pull_request

jobs:
  main:
    if: "github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'"
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: merge-dependabot-prs-command.md